Feature/10
f-lab-edu/CafeMap pull request #14
Opened 2022-11-01 19:35 UTC by dilmah0203

## [#10] 회원 정보 수정 기능 구현
- 회원 정보 수정 구현 및 테스트 코드 작성

2022-11-02 14:00 UTC, f-lab-jd requested changes

2022-11-11 13:25 UTC, dilmah0203 commented on src/main/java/com/flab/CafeMap/web/user/UserController.java
> +    @PatchMapping
해당 부분 수정하였습니다!

2022-11-11 13:26 UTC, dilmah0203 commented on src/main/java/com/flab/CafeMap/web/user/dto/UserPatchRequest.java
> +    private String modifiedBy;
수정일시와 수정자에 관한 정보는 클라이언트가 받지 않아도 됩니다~!

2022-11-12 07:55 UTC, f-lab-jd approved these changes
👍

2022-11-12 09:52 UTC, dilmah0203 commented on src/main/java/com/flab/CafeMap/domain/user/dao/UserMapper.java
> +import javax.swing.text.html.Option;
import 문 삭제하였습니다! 멘토님 merge하겠습니다!

2022-11-12 09:54 UTC, merged